Description: >
  Daniel Putzer / Network stack for a simple web app

Parameters:
  # - - General Parameters - -
  EnvironmentName:
    Description: Environment name prefix to be identify connected resources in the console
    Type: String

  # - - VPC Parameters - -
  VpcCIDR:
    Description: IP address range of VPC
    Type: String
    Default: 10.0.0.0/16

  # - - Subnet Parameters - -
  Private1CIDR:
    Description: IP address range for PrivateSubnet1
    Type: String

  Private2CIDR:
    Description: IP address range for PrivateSubnet1
    Type: String

  Public1CIDR:
    Description: IP address range for PrivateSubnet1
    Type: String

  Public2CIDR:
    Description: IP address range for PrivateSubnet1
    Type: String


Resources:

  # - -
  # VPC
  # - -
  UdagramVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} VPC
  
  # - -
  # Internet Gateway
  # - -
  UdagramInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Internet Gateway
  # Connecting Internet Gateway to VPC
  UdagramInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref UdagramVPC
      InternetGatewayId: !Ref UdagramInternetGateway


  # - -
  # Subnets
  # - -

  # - - Private Subnets - -
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ''] # Setting different AZs for subnets
      VpcId: !Ref UdagramVPC
      CidrBlock: !Ref Private1CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet 1
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ''] # Setting different AZs for subnets
      VpcId: !Ref UdagramVPC
      CidrBlock: !Ref Private2CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet 2

  # - - Public Subnets - -
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref UdagramVPC
      CidrBlock: !Ref Public1CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet 1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref UdagramVPC
      CidrBlock: !Ref Public2CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet 2


  # - -
  # NAT Gateways + Elastic IPs
  # - -

  # - - Elastic IPs - -
  Nat1EIP:
    Type: AWS::EC2::EIP
    DependsOn: UdagramInternetGateway
    Properties:
      Domain: vpc
  
  Nat2EIP:
    Type: AWS::EC2::EIP
    DependsOn: UdagramInternetGateway
    Properties:
      Domain: vpc

  # - - NAT Gateways - -
  UdagramNat1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt Nat1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  UdagramNat2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt Nat2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
  


Outputs: